Fix tabs/spaces

diff --git a/kde/sign-packages b/kde/sign-packages
--- a/kde/sign-packages
+++ b/kde/sign-packages
@@ -20,21 +20,20 @@ for i in ${depPkgName} ${optPkgName}; do
 	for a in ${arch[@]}; do
 		for j in ${pkgname[@]}; do
 			[ ! -f ${j}-${kdever}-${pkgrel}-${a}${PKGEXT} ] && scp ${server}:"~/svn-packages/${i}/${svnbranch}/${j}-${kdever}-${pkgrel}-${a}${PKGEXT}" .
-		
             
 			if [ -f ${j}-${kdever}-${pkgrel}-${a}${PKGEXT} ]; then
-			    echo "Checking packages integrity..."
+				echo "Checking packages integrity..."
     			if ! checkIntegrity ${j}-${kdever}-${pkgrel}-${a}${PKGEXT} "~/svn-packages/${i}/${svnbranch}/${j}-${kdever}-${pkgrel}-${a}${PKGEXT}"; then
-	    			echo "ERROR: ${j} ${a} corrupted"
-		    		exit 1
-		    	fi
+					echo "ERROR: ${j} ${a} corrupted"
+					exit 1
+				fi
 
-			    echo "Signing and uploading signatures..."
-    			gpg --detach-sign --use-agent ${j}-${kdever}-${pkgrel}-${a}${PKGEXT}
-	    		scp ${j}-${kdever}-${pkgrel}-${a}${PKGEXT}.sig ${server}:"~/svn-packages/${i}/${svnbranch}/"
-            else
-                echo "WARNING: ${j} ${a} not found"
-            fi
+				echo "Signing and uploading signatures..."
+				gpg --detach-sign --use-agent ${j}-${kdever}-${pkgrel}-${a}${PKGEXT}
+				scp ${j}-${kdever}-${pkgrel}-${a}${PKGEXT}.sig ${server}:"~/svn-packages/${i}/${svnbranch}/"
+			else
+				echo "WARNING: ${j} ${a} not found"
+			fi
 		done
 	done
 	_popd
@@ -49,18 +48,18 @@ if ${l10n}; then
 		[ ! -f ${j}-${kdever}-${pkgrel}-any${PKGEXT} ] && scp ${server}:"~/svn-packages/kde-l10n/${svnbranch}/${j}-${kdever}-${pkgrel}-any${PKGEXT}" .
 
 		if [ -f ${j}-${kdever}-${pkgrel}-any${PKGEXT} ]; then
-		    echo "Checking packages integrity..."
-		    if ! checkIntegrity ${j}-${kdever}-${pkgrel}-any${PKGEXT} "~/svn-packages/kde-l10n/${svnbranch}/${j}-${kdever}-${pkgrel}-any${PKGEXT}"; then
-			    echo "ERROR: ${j} corrupted"
-			    exit 1
-		    fi
+			echo "Checking packages integrity..."
+			if ! checkIntegrity ${j}-${kdever}-${pkgrel}-any${PKGEXT} "~/svn-packages/kde-l10n/${svnbranch}/${j}-${kdever}-${pkgrel}-any${PKGEXT}"; then
+				echo "ERROR: ${j} corrupted"
+				exit 1
+			fi
 
-		    echo "Signing and uploading signatures..."
-		    gpg --detach-sign --use-agent ${j}-${kdever}-${pkgrel}-any${PKGEXT}
-		    scp ${j}-${kdever}-${pkgrel}-any${PKGEXT}.sig ${server}:"~/svn-packages/kde-l10n/${svnbranch}/"
-        else
-            echo "WARNING: ${j} ${a} not found"
-        fi
+			echo "Signing and uploading signatures..."
+			gpg --detach-sign --use-agent ${j}-${kdever}-${pkgrel}-any${PKGEXT}
+			scp ${j}-${kdever}-${pkgrel}-any${PKGEXT}.sig ${server}:"~/svn-packages/kde-l10n/${svnbranch}/"
+		else
+			echo "WARNING: ${j} ${a} not found"
+		fi
 	done
 	_popd
 fi
