Sync release-rebuilds with release-packages

diff --git a/scripts/release-rebuilds b/scripts/release-rebuilds
--- a/scripts/release-rebuilds
+++ b/scripts/release-rebuilds
@@ -5,10 +5,20 @@ SCRIPTPATH=$(dirname "$SCRIPT")
 
 . ${SCRIPTPATH}/common
 
+basedir=${PWD}
+
 cd ${packages_dir}
 
 for i in $(cat ${scriptroot}/package-list/${suite}/rebuild.list); do
   _pushd ${i}
-    pkgctl release "$@" || exit 1
+    pkgctl release "$@" || echo $i >> ${basedir}/broken-releases
   _popd
 done
+
+cd ${basedir}
+if [ -s broken-releases ]; then
+  echo "The following packages could not be released:"
+  cat broken-releases
+else
+  echo "All packages released successfully!"
+fi
